### ISSUE TITLE
Интеграция discord.js-selfbot-v13 и discord.js-selfbot-rpc

### ISSUE THREAD

**Issue by menleev** [qweme32/YandexMusicRPC#1]
Добрый день, понимаю что гит уже наверное заброшен, но если прочитаете этот запрос и добавить указанные в нём возможности будет очень даже отлично^^

Библиотеки `npm i discord.js-selfbot-rpc` и `npm i discord.js-selfbot-v13` позволяют обычному юзеру применять статус слушает и т.д, вы можете интегрировать их в текущую версию с установкой токена discord пользователя?

**Comment by qweme32** [comment]
Привет, а для чего это нужно?

**Comment by menleev** [comment]
Чтобы красиво смотрелось, ибо приятно когда статус `слушает` а не `играет` + модификация (добавление) кнопок прослушать трек и т.д

**Comment by qweme32** [comment]
слушает не получиться сделать, а кнопки я и так могу добавить

**Comment by menleev** [comment]
Получится сделать, `discord.js-selfbot-rpc` позволяет использовать всё вместе, по этому можно выставлять статус слушает и втыкать rpc

**Comment by qweme32** [comment]
Закрыто
